# Generated by Django 5.0 on 2023-12-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('length', models.FloatField(default=1)),
                ('breadth', models.FloatField(default=1)),
                ('height', models.FloatField(default=1)),
                ('area', models.FloatField(default=1)),
                ('volume', models.FloatField(default=1)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
