# Generated by Django 5.0 on 2023-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0003_alter_box_area_alter_box_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='area',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='box',
            name='volume',
            field=models.FloatField(default=1),
        ),
    ]
